"""Adding User and Task Relationship

Revision ID: 06dc6168a451
Revises: 7871be2cb7ac
Create Date: 2025-09-04 07:29:14.615223

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel                     



# revision identifiers, used by Alembic.
revision: str = '06dc6168a451'
down_revision: Union[str, Sequence[str], None] = '7871be2cb7ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('user_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'tasks', 'users', ['user_id'], ['user_uid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'user_id')
    # ### end Alembic commands ###
