"""add_password_hash

Revision ID: 4ca40ea7caeb
Revises: 5e47d43c8038
Create Date: 2025-08-26 12:41:30.697745

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel                     



# revision identifiers, used by Alembic.
revision: str = '4ca40ea7caeb'
down_revision: Union[str, Sequence[str], None] = '5e47d43c8038'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###
