"""max_length

Revision ID: 7871be2cb7ac
Revises: c8980b75cf27
Create Date: 2025-08-31 20:25:00.362151

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel                     



# revision identifiers, used by Alembic.
revision: str = '7871be2cb7ac'
down_revision: Union[str, Sequence[str], None] = 'c8980b75cf27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
