"""adding is_legal field

Revision ID: 8c18b2706bfc
Revises: eb94a955f930
Create Date: 2025-08-28 16:01:34.473784

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel                     



# revision identifiers, used by Alembic.
revision: str = '8c18b2706bfc'
down_revision: Union[str, Sequence[str], None] = 'eb94a955f930'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_legal', sa.BOOLEAN(), server_default='true', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_legal')
    # ### end Alembic commands ###
