"""adding tasks table

Revision ID: e409dc3f7044
Revises: 8c18b2706bfc
Create Date: 2025-08-31 20:03:23.870011

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel                     

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e409dc3f7044'
down_revision: Union[str, Sequence[str], None] = '8c18b2706bfc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tasks',
    sa.Column('task_uid', sa.UUID(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('deadline', sa.DateTime(), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('progress_rate', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('task_uid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tasks')
    # ### end Alembic commands ###
