"""adding role

Revision ID: eb94a955f930
Revises: 4ca40ea7caeb
Create Date: 2025-08-27 09:47:48.206848

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel                     



# revision identifiers, used by Alembic.
revision: str = 'eb94a955f930'
down_revision: Union[str, Sequence[str], None] = '4ca40ea7caeb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', sa.VARCHAR(), server_default='user', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    # ### end Alembic commands ###
